# Generated by Django 5.0.3 on 2025-05-09 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_escola', '0001_initial'),
    ]

    operations = [
    ]
