# Generated by Django 5.0.3 on 2025-05-11 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_escola', '0003_matricula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudante',
            name='cpf',
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
